### ISSUE TITLE
上午好，请教下管理后台怎么同接口测用例工程做关联呢

### ISSUE THREAD

**Issue by mrzhoux** [hanwenlu2016/Salvation#1]
上午好 打搅了 我部署了后台工程，但是不知道怎么同接口测试用例的工程做关联和管理呢
非常期待您的回复 感谢

**Comment by hanwenlu2016** [comment]
> 上午好打搅了我部署了后台工程，但不知道怎么接口用例测试的工程做关联和管理呢 非常期待您的回复感谢

邮件已经回复

**Comment by prelongs** [comment]
Hi, @hanwenlu2016 能否也发我一份 后台同接口测试用例的工程做关联和管理 的教程 
非常期待您的回复 感谢！
